/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      spacing: {
        'tma-safe': 'var(--tma-top-padding)',
      },
      colors: {
        // Direct OneHouse tokens
        'bg-base': '#090b0e',
        'surface': '#14171c',
        'surface-elevated': '#181c23',
        'surface-subtle': '#252c37',
        'surface-glass': 'rgba(20, 23, 28, 0.94)',
        'accent': '#c0ff00',
        'accent-hover': '#aee600',
        'accent-subtle': 'rgba(192, 255, 0, 0.15)',
        'text-muted': '#8e8e93',
        'border-subtle': 'rgba(255, 255, 255, 0.04)',

        // OneWebUI prefixed tokens
        'oneweb-bg': 'var(--oneweb-bg, #090b0e)',
        'oneweb-bg-subtle': 'var(--oneweb-bg-subtle, #050709)',
        'oneweb-surface': 'var(--oneweb-surface, #14171c)',
        'oneweb-surface-elevated': 'var(--oneweb-surface-elevated, #181c23)',
        'oneweb-surface-subtle': 'var(--oneweb-surface-subtle, #252c37)',
        'oneweb-surface-glass': 'var(--oneweb-surface-glass, rgba(20, 23, 28, 0.94))',
        'oneweb-border': 'var(--oneweb-border, rgba(255, 255, 255, 0.10))',
        'oneweb-border-subtle': 'var(--oneweb-border-subtle, rgba(255, 255, 255, 0.04))',
        'oneweb-border-strong': 'var(--oneweb-border-strong, rgba(255, 255, 255, 0.15))',
        'oneweb-border-accent': 'var(--oneweb-border-accent, rgba(192, 255, 0, 0.25))',
        'oneweb-accent': 'var(--oneweb-accent, #c0ff00)',
        'oneweb-accent-hover': 'var(--oneweb-accent-hover, #aee600)',
        'oneweb-accent-subtle': 'var(--oneweb-accent-subtle, rgba(192, 255, 0, 0.15))',
        'oneweb-text-primary': 'var(--oneweb-text-primary, #ffffff)',
        'oneweb-text-secondary': 'var(--oneweb-text-secondary, #8e8e93)',
        'oneweb-text-muted': 'var(--oneweb-text-muted, #8e8e93)',
        'oneweb-text-accent': 'var(--oneweb-text-accent, #c0ff00)',
        'oneweb-text-inverse': 'var(--oneweb-text-inverse, #090b0e)',
        'oneweb-status-success': 'var(--oneweb-status-success, #1bd96a)',
        'oneweb-status-warning': 'var(--oneweb-status-warning, #fbbf24)',
        'oneweb-status-danger': 'var(--oneweb-status-danger, #ef4444)',

        // Nested namespace support
        oneweb: {
          bg: 'var(--oneweb-bg, #090b0e)',
          'bg-subtle': 'var(--oneweb-bg-subtle, #050709)',
          surface: 'var(--oneweb-surface, #14171c)',
          'surface-elevated': 'var(--oneweb-surface-elevated, #181c23)',
          'surface-subtle': 'var(--oneweb-surface-subtle, #252c37)',
          'surface-glass': 'var(--oneweb-surface-glass, rgba(20, 23, 28, 0.94))',
          border: 'var(--oneweb-border, rgba(255, 255, 255, 0.10))',
          'border-subtle': 'var(--oneweb-border-subtle, rgba(255, 255, 255, 0.04))',
          'border-strong': 'var(--oneweb-border-strong, rgba(255, 255, 255, 0.15))',
          'border-accent': 'var(--oneweb-border-accent, rgba(192, 255, 0, 0.25))',
          accent: 'var(--oneweb-accent, #c0ff00)',
          'accent-hover': 'var(--oneweb-accent-hover, #aee600)',
          'accent-subtle': 'var(--oneweb-accent-subtle, rgba(192, 255, 0, 0.15))',
          text: {
            primary: 'var(--oneweb-text-primary, #ffffff)',
            secondary: 'var(--oneweb-text-secondary, #8e8e93)',
            muted: 'var(--oneweb-text-muted, #8e8e93)',
            accent: 'var(--oneweb-text-accent, #c0ff00)',
            inverse: 'var(--oneweb-text-inverse, #090b0e)',
          },
          status: {
            success: 'var(--oneweb-status-success, #1bd96a)',
            warning: 'var(--oneweb-status-warning, #fbbf24)',
            danger: 'var(--oneweb-status-danger, #ef4444)',
          },
        },
      },
      fontFamily: {
        sans: ['"Wix Madefor Display"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        'oneweb-sans': ['"Wix Madefor Display"', 'sans-serif'],
        'oneweb-mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        'xl': '12px',
        '2xl': '16px',
        '3xl': '28px',
        'card': '28px',
        'sheet': '32px',
        'modal': '32px',
        'oneweb-min': '12px',
        'oneweb-lg': '12px',
        'oneweb-xl': '16px',
        'oneweb-2xl': '20px',
        'oneweb-3xl': '28px',
        'oneweb-card': '28px',
        'oneweb-sheet': '32px',
        'oneweb-modal': '32px',
        'oneweb-full': '9999px',
      },
      boxShadow: {
        'oneweb-sm': '0 1px 2px 0 rgba(0, 0, 0, 0.5)',
        'oneweb-md': '0 4px 12px 0 rgba(0, 0, 0, 0.55)',
        'oneweb-lg': '0 8px 24px 0 rgba(0, 0, 0, 0.65)',
        'oneweb-accent-glow': '0 0 16px rgba(192, 255, 0, 0.35)',
        'oneweb-sheet': '0 -12px 48px rgba(0, 0, 0, 0.85)',
        'oneweb-modal': '0 12px 40px rgba(0, 0, 0, 0.80)',
      },
      animation: {
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        'welcome-glow': 'welcomeGlow 1.5s ease-in-out infinite alternate',
      },
      keyframes: {
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        welcomeGlow: {
          '0%': { 'text-shadow': '0 0 8px rgba(192, 255, 0, 0.1)' },
          '100%': { 'text-shadow': '0 0 24px rgba(192, 255, 0, 0.4), 0 0 48px rgba(192, 255, 0, 0.15)' },
        },
      },
    },
  },
  plugins: [],
};
